### PR TITLE
adding cymetric plus some minor fixes

### PR DESCRIPTION
**Pull request by opotowsky**

### CODE REVIEW

**Comment by opotowsky** [comment]
@gidden regarding the maintenance.sh (line 131) do I add cymetric's path under that?

**Comment by gidden** [comment]
You do not need to add anything to maintenence if there is none for the
package. Does cymetric have a conda package? If so, you will need to update
the conda_upload.sh script and documentation. The same should probably go
for the make_release_notes.sh utility as well.

On Wed, May 6, 2015 at 2:39 PM, opotowsky notifications@github.com wrote:

> @gidden https://github.com/gidden regarding the maintenance.sh (line
> 131) do I add cymetric's path under that?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gidden/cyclus.github.com/pull/1#issuecomment-99583165
> .

## 

Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by opotowsky** [comment]
Cymetric does have a conda package for "0.0". 

I think I'm missing something - I'm not sure where these files live. But I will update the documentation here.

**Comment by opotowsky** [comment]
oh these are just scripts the release manager writes on their own? I thought there were templates somewhere

**Comment by gidden** [comment]
They are currently in cyclus/ciclus#63

On Wed, May 6, 2015 at 3:20 PM, opotowsky notifications@github.com wrote:

> oh these are just scripts the release manager writes on their own? I
> thought there were templates somewhere
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gidden/cyclus.github.com/pull/1#issuecomment-99594255
> .

## 

Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by opotowsky** [comment]
Alrighty, this should pair up with https://github.com/gidden/ciclus/pull/2

**Comment by gidden** [comment]
thanks @opotowsky!

**Pull request merged**
